version: "3.4"

services:
  bot-channel-generator:
    env_file:
    - .env.local
    image: ghcr.io/noblepierre/bot-channel-generator:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 15 
        window: 15s
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}